feat(api): setup crud view
WhatToWatch-Groupe4/monorepo pull request #50
Opened 2021-02-18 11:58 UTC by RomainFon

2021-02-18 13:20 UTC, agravelot requested changes

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.controller.ts
> +  async findAll(@Param('uid') uid: string): Promise<View[]> {
`findAll` sur `/views/:uid` ?

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.entity.ts
> +  id: number;
Dans le controller c'est un uuid et la un id standard

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.controller.ts
> +    } catch (e) {
A quoi sert ce catch on ne fait pas de requête axios ici

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.controller.ts
> +    } catch (e) {
A quoi sert ce catch on ne fait pas de requête axios ici

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.controller.ts
> +    } catch (e) {
A quoi sert ce catch on ne fait pas de requête axios ici

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.entity.ts
> +  uid: string;
Je présume que c'est pour l'utilisateur, éventuellement renommer `user_uuid`

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.controller.ts
> +  @Get(':uid')
`uid` n'est pas une clé unique dans l'entité, cela ne peut être utiliser pour le routing

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.controller.ts
> +  async findOne(@Req() req: Request): Promise<boolean> {
Tu peux get les params avec l'annotation `@Param` comme ce que tu as fait pour le delete

2021-02-18 13:20 UTC, agravelot commented on apps/api/src/views/views.controller.ts
> +      return !!(await this.viewsService.findOne(uid, movie));
Pourquoi retourner un boolean ?

2021-02-18 13:24 UTC, RomainFon commented on apps/api/src/views/views.controller.ts
> +  async findAll(@Param('uid') uid: string): Promise<View[]> {
Pour le listing de tous les films "vue" d'un utilisateur

2021-02-18 13:26 UTC, RomainFon commented on apps/api/src/views/views.controller.ts
> +      return !!(await this.viewsService.findOne(uid, movie));
On va effectivement retourner le View directement.

2021-02-18 13:32 UTC, RomainFon commented on apps/api/src/views/views.controller.ts
> +    } catch (e) {
Yep en effet...

2021-02-18 13:32 UTC, RomainFon commented on apps/api/src/views/views.controller.ts
> +    } catch (e) {
Yep en effet...

2021-02-18 13:32 UTC, RomainFon commented on apps/api/src/views/views.controller.ts
> +    } catch (e) {
Yep en effet...

2021-02-18 13:35 UTC, RomainFon commented on apps/api/src/views/views.controller.ts
> +  @Get(':uid')
C'est pour récupérer l'ensemble des films vus d'un user

2021-02-18 13:38 UTC, RomainFon commented on apps/api/src/views/views.controller.ts
> +  async findOne(@Req() req: Request): Promise<boolean> {
Je voulais les récupérer dans le body

2021-02-18 13:38 UTC, RomainFon commented on apps/api/src/views/views.entity.ts
> +  uid: string;
Oui plus intuitif

2021-02-19 11:23 UTC, agravelot requested changes

2021-02-19 11:23 UTC, agravelot commented on apps/api/src/views/views.controller.ts
> +  @Get(':movie/:user_uuid')
Pourquoi pas passer le `user_uuid` en Query param au lieu de le mettre dans le path

2021-02-19 11:23 UTC, agravelot commented on apps/api/src/views/views.entity.ts
> +export class View {
On devrait pouvoir mettre une contrainte unique composite sur `movie` et `user_uuid` pour éviter qu'un utilisateur l'ajoute en double.

2021-02-19 11:23 UTC, agravelot commented on apps/api/src/views/views.service.ts
> +    return this.viewRepository.save(view);
Tu peux simplifier par :
```
return this.viewRepository.save({ user_uuid, movie });
```

2021-02-19 11:23 UTC, agravelot commented on apps/web/src/components/ButtonView.tsx
> +  const [view, setView] = useState(0);
Pourquoi pas mettre un boolean ?

2021-02-19 11:23 UTC, agravelot commented on apps/web/src/components/ButtonView.tsx
> +    if (keycloak.authenticated) {
Je mettrais ce if plus dans le useEffect

2021-02-19 11:23 UTC, agravelot commented on apps/web/src/components/ButtonView.tsx
> +function ButtonView(props: any) {
Il faudrait typer les props avec une interface, voir ma branche si besoin

2021-02-19 11:32 UTC, RomainFon commented on apps/web/src/components/ButtonView.tsx
> +  const [view, setView] = useState(0);
Pour éviter de faire deux variables. Je set l'id dans le view si j'en ai récupéré un

2021-02-19 11:46 UTC, RomainFon commented on apps/api/src/views/views.controller.ts
> +  @Get(':movie/:user_uuid')
Yep modifié

2021-02-19 11:46 UTC, RomainFon commented on apps/api/src/views/views.entity.ts
> +export class View {
Yep modifié

2021-02-19 11:46 UTC, RomainFon commented on apps/api/src/views/views.service.ts
> +    return this.viewRepository.save(view);
Yep modifié

2021-02-19 11:46 UTC, RomainFon commented on apps/web/src/components/ButtonView.tsx
> +function ButtonView(props: any) {
Yep modifié

2021-02-19 11:48 UTC, RomainFon commented on apps/web/src/components/ButtonView.tsx
> +    if (keycloak.authenticated) {
Yep ça obligera à pas appeler la fonction pour rien

2021-02-19 12:50 UTC, agravelot commented on apps/web/src/components/ButtonView.tsx
> +  const [view, setView] = useState(0);
Peut-être renommer en `viewId` alors avec une valeur null par défaut

2021-02-19 13:17 UTC, agravelot approved these changes

2021-02-19 13:17 UTC, merged